require_relative 'pages/login'
require_relative 'pages/login_with'
require_relative 'pages/login_with_email'
require_relative 'pages/signup_with'
require_relative 'pages/workout'
require_relative 'common'
